volumes:
  loki-data:
  tempo-data:

networks:
  observability:

services:
  # loki-chown-volume:
  #   image: busybox:1.37
  #   user: "0:0"
  #   command: ["sh","-c","chown -R 10001:10001 /tmp/loki"]
  #   volumes:
  #     - loki-data:/tmp/loki
  #   restart: no

  loki:
    # depends_on:
    #   - loki-chown-volume
    image: grafana/loki:3.4.1
    command: ["-config.file=/etc/loki.yml"]
    # note: too lazy to work around loki uid:gid permissions, would have to introduce
    # a new container to chown -R the paths in the loki.yml...
    user: root
    ports:
      - 3100:3100
    volumes:
      - loki-data:/tmp/loki
      - ./configs/loki.yml:/etc/loki.yml:ro
    restart: unless-stopped
    networks:
      - observability

  prometheus:
    image: prom/prometheus:v3.6.0
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus.yml:ro
    networks:
      - observability

  tempo:
    image: grafana/tempo:2.8.2
    command: [ "-config.file=/etc/tempo.yml" ]
    # note: too lazy to work around loki uid:gid permissions
    user: root
    ports:
      - "3200" # tempo
      - "4317" # otlp grpc
    volumes:
      - tempo-data:/var/tempo
      - ./configs/tempo.yml:/etc/tempo.yml:ro
    networks:
      - observability

  grafana:
    depends_on:
      - loki
      - tempo
      - prometheus
    image: grafana/grafana:11.5
    ports:
      - 3000:3000
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor,metricsSummary,alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    volumes:
      - type: bind
        bind:
          create_host_path: false
        read_only: true
        source: configs/grafana-datasources.yml
        target: /etc/grafana/provisioning/datasources/datasources.yaml
    restart: unless-stopped
    networks:
      - observability

  otelcol:
    depends_on:
      - loki
      - tempo
    image: otel/opentelemetry-collector-contrib:0.135.0
    pull_policy: build
    command: ["--config=/etc/otelcol.yml"]
    # ports:
    #   - 1888:1888 # pprof extension
    #   - 13133:13133 # health_check extension
    #   - 55679:55679 # zpages extension
    #   - 8888:8888 # Prometheus metrics exposed by the Collector
    #   - 8889:8889 # Prometheus exporter metrics
    #   - 4317:4317 # OTLP gRPC receiver
    #   - 4318:4318 # OTLP http receiver
    volumes:
      - ./configs/otelcol.yml:/etc/otelcol.yml:ro
    restart: unless-stopped
    networks:
      - observability

  ginapp:
    depends_on:
      - otelcol
    build:
      context: .
      dockerfile: ./Dockerfile
    pull_policy: build
    ports:
      - 8080:8080
    environment:
      # standard otel env to tell it the sdk to send to this endpoint
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otelcol:4318
      OTEL_LOG_LEVEL: info
      OTEL_SERVICE_NAME: ginapp
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment.name=dev
    networks:
      - observability
