receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog:
    include:
      #- /var/log/pods/*/*/*.log   # Kubernetes pod logs
      - /var/log/*.log
    start_at: beginning

processors:
  batch:

  resource:
    attributes:
      - key: service.namespace
        value: go-playground
        action: upsert

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
  debug:
    #verbosity: basic
    verbosity: normal
    #verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters:
        - debug
        - otlp/tempo
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - debug
    logs:
      receivers: [otlp, filelog]
      processors: [batch, resource]
      exporters:
        - debug
        - otlphttp/loki
