receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog:
    include:
      #- /var/log/pods/*/*/*.log   # Kubernetes pod logs
      - /var/log/*.log
    start_at: beginning

processors:
  batch:
  resource:
    attributes:
      - key: service.namespace
        value: go-playground
        action: upsert

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
  prometheus:
    endpoint: 0.0.0.0:8889  # collector serves metrics here
    namespace: go-playground
    # Include resource attrs as metric labels (useful for service.name, etc.)
    resource_to_telemetry_conversion:
      enabled: true
  debug:
    #verbosity: basic
    verbosity: normal
    #verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters:
        - debug
        - otlp/tempo
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - debug
        - prometheus
    logs:
      receivers: [otlp, filelog]
      processors: [resource, batch]
      exporters:
        - debug
        - otlphttp/loki
