# See https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI

on:
  push:
    branches: [ "main", "env/**/*" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.4.0
      with:
        go-version-file: go.mod
        cache: false
        #cache-dependency-path: go.sum

    - name: Build
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.4.0
      with:
        go-version-file: go.mod
        cache: false
        #cache-dependency-path: go.sum

    - name: Test
      run: go test -v ./...

